# AI sector top US-listed companies. Names are bilingual (中文 English) for display.
AI_COMPANIES = [
    # ── Priority (user-pinned, shown first) ──
    {"name": "英伟达 NVIDIA",   "ticker": "NVDA",  "keywords": ["NVIDIA", "NVDA"]},
    {"name": "谷歌 Alphabet",   "ticker": "GOOGL", "keywords": ["Google", "Alphabet", "GOOGL", "Gemini", "DeepMind"]},
    {"name": "美光 Micron",     "ticker": "MU",    "keywords": ["Micron", "MU", "HBM memory"]},
    {"name": "闪迪 SanDisk",    "ticker": "SNDK",  "keywords": ["SanDisk", "SNDK"]},
    {"name": "迈威尔 Marvell",  "ticker": "MRVL",  "keywords": ["Marvell", "MRVL"]},
    {"name": "AMD",             "ticker": "AMD",   "keywords": ["AMD", "Advanced Micro Devices"]},

    # Mega cap
    {"name": "微软 Microsoft",  "ticker": "MSFT",  "keywords": ["Microsoft", "MSFT", "Azure AI", "Copilot"]},
    {"name": "苹果 Apple",      "ticker": "AAPL",  "keywords": ["Apple", "AAPL", "Apple Intelligence"]},
    {"name": "亚马逊 Amazon",   "ticker": "AMZN",  "keywords": ["Amazon", "AMZN", "AWS", "Bedrock AI"]},
    {"name": "Meta (脸书)",     "ticker": "META",  "keywords": ["Meta", "META", "Llama", "Facebook AI"]},
    {"name": "台积电 TSMC",     "ticker": "TSM",   "keywords": ["TSMC", "TSM", "Taiwan Semiconductor"]},
    {"name": "博通 Broadcom",   "ticker": "AVGO",  "keywords": ["Broadcom", "AVGO"]},
    {"name": "特斯拉 Tesla",    "ticker": "TSLA",  "keywords": ["Tesla", "TSLA", "Optimus robot", "FSD"]},

    # Large cap
    {"name": "甲骨文 Oracle",   "ticker": "ORCL",  "keywords": ["Oracle", "ORCL", "Oracle AI"]},
    {"name": "Salesforce",      "ticker": "CRM",   "keywords": ["Salesforce", "CRM", "Agentforce"]},
    {"name": "英特尔 Intel",    "ticker": "INTC",  "keywords": ["Intel", "INTC", "Gaudi"]},
    {"name": "高通 Qualcomm",   "ticker": "QCOM",  "keywords": ["Qualcomm", "QCOM", "Snapdragon"]},
    {"name": "IBM",             "ticker": "IBM",   "keywords": ["IBM", "watsonx"]},
    {"name": "ServiceNow",      "ticker": "NOW",   "keywords": ["ServiceNow", "NOW"]},
    {"name": "Palantir",        "ticker": "PLTR",  "keywords": ["Palantir", "PLTR"]},
    {"name": "Snowflake",       "ticker": "SNOW",  "keywords": ["Snowflake", "SNOW"]},
    {"name": "Cloudflare",      "ticker": "NET",   "keywords": ["Cloudflare", "NET"]},
    {"name": "Datadog",         "ticker": "DDOG",  "keywords": ["Datadog", "DDOG"]},
    {"name": "MongoDB",         "ticker": "MDB",   "keywords": ["MongoDB", "MDB"]},
    {"name": "CrowdStrike",     "ticker": "CRWD",  "keywords": ["CrowdStrike", "CRWD"]},
    {"name": "Palo Alto 派拓",  "ticker": "PANW",  "keywords": ["Palo Alto Networks", "PANW"]},
    {"name": "Workday",         "ticker": "WDAY",  "keywords": ["Workday", "WDAY"]},
    {"name": "Intuit",          "ticker": "INTU",  "keywords": ["Intuit", "INTU"]},
    {"name": "奥多比 Adobe",    "ticker": "ADBE",  "keywords": ["Adobe", "ADBE", "Firefly"]},
    {"name": "新思 Synopsys",   "ticker": "SNPS",  "keywords": ["Synopsys", "SNPS"]},
    {"name": "铿腾 Cadence",    "ticker": "CDNS",  "keywords": ["Cadence", "CDNS"]},
    {"name": "应用材料 AMAT",   "ticker": "AMAT",  "keywords": ["Applied Materials", "AMAT"]},
    {"name": "阿斯麦 ASML",     "ticker": "ASML",  "keywords": ["ASML"]},
    {"name": "泛林 Lam Research","ticker": "LRCX",  "keywords": ["Lam Research", "LRCX"]},
    {"name": "科磊 KLA",        "ticker": "KLAC",  "keywords": ["KLA", "KLAC"]},
    {"name": "Arm 公司",        "ticker": "ARM",   "keywords": ["Arm Holdings", "ARM"]},

    # AI-focused mid cap
    {"name": "C3.ai",           "ticker": "AI",    "keywords": ["C3.ai", " AI "]},
    {"name": "SoundHound AI",   "ticker": "SOUN",  "keywords": ["SoundHound", "SOUN"]},
    {"name": "超微电脑 SMCI",   "ticker": "SMCI",  "keywords": ["Super Micro", "SuperMicro", "SMCI"]},
    {"name": "IonQ",            "ticker": "IONQ",  "keywords": ["IonQ", "IONQ"]},
    {"name": "Rigetti 量子",    "ticker": "RGTI",  "keywords": ["Rigetti", "RGTI"]},
    {"name": "量子计算公司 QUBT","ticker": "QUBT", "keywords": ["Quantum Computing Inc", "QUBT"]},
    {"name": "BigBear.ai",      "ticker": "BBAI",  "keywords": ["BigBear", "BBAI"]},
    {"name": "Recursion 制药",  "ticker": "RXRX",  "keywords": ["Recursion", "RXRX"]},
    {"name": "Scale AI",        "ticker": "S",     "keywords": ["Scale AI"]},
    {"name": "Veeva 系统",      "ticker": "VEEV",  "keywords": ["Veeva", "VEEV"]},
    {"name": "Twilio",          "ticker": "TWLO",  "keywords": ["Twilio", "TWLO"]},
    {"name": "UiPath",          "ticker": "PATH",  "keywords": ["UiPath", "PATH"]},
    {"name": "GitLab",          "ticker": "GTLB",  "keywords": ["GitLab", "GTLB"]},
    {"name": "Elastic",         "ticker": "ESTC",  "keywords": ["Elastic", "ESTC"]},
    {"name": "HashiCorp",       "ticker": "HCP",   "keywords": ["HashiCorp", "HCP"]},
    {"name": "Confluent",       "ticker": "CFLT",  "keywords": ["Confluent", "CFLT"]},
    {"name": "Informatica",     "ticker": "INFA",  "keywords": ["Informatica", "INFA"]},
    {"name": "Verint 系统",     "ticker": "VRNT",  "keywords": ["Verint", "VRNT"]},
    {"name": "Ceridian",        "ticker": "CDAY",  "keywords": ["Ceridian", "CDAY"]},
    {"name": "Sprinklr",        "ticker": "CXM",   "keywords": ["Sprinklr", "CXM"]},
    {"name": "Samsara",         "ticker": "IOT",   "keywords": ["Samsara", "IOT"]},
    {"name": "Asana",           "ticker": "ASAN",  "keywords": ["Asana", "ASAN"]},
    {"name": "monday.com",      "ticker": "MNDY",  "keywords": ["monday.com", "MNDY"]},
    {"name": "Zendesk",         "ticker": "ZEN",   "keywords": ["Zendesk", "ZEN"]},
    {"name": "Brainware AI",    "ticker": "BWAI",  "keywords": ["Brainware", "BWAI"]},
    {"name": "Luminar 激光雷达","ticker": "LAZR",  "keywords": ["Luminar", "LAZR"]},
    {"name": "Mobileye",        "ticker": "MBLY",  "keywords": ["Mobileye", "MBLY"]},
    {"name": "通用汽车 Cruise", "ticker": "GM",    "keywords": ["Cruise autonomous", "GM AI"]},
    {"name": "Aurora 自动驾驶", "ticker": "AUR",   "keywords": ["Aurora Innovation", "AUR"]},
    {"name": "Symbotic",        "ticker": "SYM",   "keywords": ["Symbotic", "SYM"]},
    {"name": "LegalZoom",       "ticker": "LZ",    "keywords": ["LegalZoom", "LZ"]},
    {"name": "多邻国 Duolingo", "ticker": "DUOL",  "keywords": ["Duolingo", "DUOL"]},
    {"name": "Chegg",           "ticker": "CHGG",  "keywords": ["Chegg", "CHGG"]},
    {"name": "Coursera",        "ticker": "COUR",  "keywords": ["Coursera", "COUR"]},
    {"name": "2U 公司",         "ticker": "TWOU",  "keywords": ["2U Inc", "TWOU"]},
    {"name": "Genie Energy",    "ticker": "GNE",   "keywords": ["Genie Energy", "GNE"]},
    {"name": "Veritone",        "ticker": "VERI",  "keywords": ["Veritone", "VERI"]},
    {"name": "LivePerson",      "ticker": "LPSN",  "keywords": ["LivePerson", "LPSN"]},
    {"name": "Edgio",           "ticker": "EGIO",  "keywords": ["Edgio", "EGIO"]},
    {"name": "Appian",          "ticker": "APPN",  "keywords": ["Appian", "APPN"]},
    {"name": "Olo",             "ticker": "OLO",   "keywords": ["Olo", " OLO "]},
    {"name": "Five9",           "ticker": "FIVN",  "keywords": ["Five9", "FIVN"]},
    {"name": "NICE 公司",       "ticker": "NICE",  "keywords": ["NICE Ltd", "NICE"]},
    {"name": "Bandwidth",       "ticker": "BAND",  "keywords": ["Bandwidth Inc", "BAND"]},
    {"name": "Lunit",           "ticker": "LUNIT", "keywords": ["Lunit"]},
    {"name": "iRobot",          "ticker": "IRBT",  "keywords": ["iRobot", "IRBT"]},
    {"name": "直觉外科 ISRG",   "ticker": "ISRG",  "keywords": ["Intuitive Surgical", "ISRG", "da Vinci"]},
    {"name": "波士顿科学 BSX",  "ticker": "BSX",   "keywords": ["Boston Scientific", "BSX"]},
    {"name": "美敦力 Medtronic","ticker": "MDT",   "keywords": ["Medtronic", "MDT"]},
    {"name": "戴尔 Dell",       "ticker": "DELL",  "keywords": ["Dell AI", "Dell NVDA", "Dell PowerEdge AI"]},
    {"name": "慧与 HPE",        "ticker": "HPE",   "keywords": ["HPE AI", "HP Enterprise AI"]},
    {"name": "Pure Storage",    "ticker": "PSTG",  "keywords": ["Pure Storage", "PSTG"]},
    {"name": "NetApp",          "ticker": "NTAP",  "keywords": ["NetApp", "NTAP"]},
    {"name": "Roper 科技",      "ticker": "ROP",   "keywords": ["Roper Technologies", "ROP"]},
    {"name": "Tyler 科技",      "ticker": "TYL",   "keywords": ["Tyler Technologies", "TYL"]},
    {"name": "SS&C",            "ticker": "SSNC",  "keywords": ["SS&C", "SSNC"]},
    {"name": "OpenAI（未上市）","ticker": "N/A",   "keywords": ["OpenAI", "ChatGPT", "GPT-5", "o3"]},
    {"name": "Anthropic（未上市）","ticker": "N/A","keywords": ["Anthropic", "Claude AI"]},
    {"name": "xAI（未上市）",   "ticker": "N/A",   "keywords": ["xAI", "Grok AI", "Elon Musk AI"]},
    {"name": "Mistral（未上市）","ticker": "N/A",  "keywords": ["Mistral AI"]},
    {"name": "Cohere（未上市）", "ticker": "N/A",  "keywords": ["Cohere AI"]},
    {"name": "Perplexity（未上市）","ticker": "N/A","keywords": ["Perplexity AI"]},
]
