# AI sector top 100 US-listed companies (by market cap, as of 2025)
AI_COMPANIES = [
    # ── Priority (user-pinned, shown first) ──
    {"name": "英伟达 NVIDIA",   "ticker": "NVDA",  "keywords": ["NVIDIA", "NVDA"]},
    {"name": "谷歌 Alphabet",   "ticker": "GOOGL", "keywords": ["Google", "Alphabet", "GOOGL", "Gemini", "DeepMind"]},
    {"name": "美光 Micron",     "ticker": "MU",    "keywords": ["Micron", "MU", "HBM memory"]},
    {"name": "闪迪 SanDisk",    "ticker": "SNDK",  "keywords": ["SanDisk", "SNDK"]},
    {"name": "迈威尔 Marvell",  "ticker": "MRVL",  "keywords": ["Marvell", "MRVL"]},
    {"name": "AMD",             "ticker": "AMD",   "keywords": ["AMD", "Advanced Micro Devices"]},

    # Mega cap
    {"name": "Microsoft",       "ticker": "MSFT",  "keywords": ["Microsoft", "MSFT", "Azure AI", "Copilot"]},
    {"name": "Apple",           "ticker": "AAPL",  "keywords": ["Apple", "AAPL", "Apple Intelligence"]},
    {"name": "Amazon",          "ticker": "AMZN",  "keywords": ["Amazon", "AMZN", "AWS", "Bedrock AI"]},
    {"name": "Meta",            "ticker": "META",  "keywords": ["Meta", "META", "Llama", "Facebook AI"]},
    {"name": "TSMC (ADR)",      "ticker": "TSM",   "keywords": ["TSMC", "TSM", "Taiwan Semiconductor"]},
    {"name": "Broadcom",        "ticker": "AVGO",  "keywords": ["Broadcom", "AVGO"]},
    {"name": "Tesla",           "ticker": "TSLA",  "keywords": ["Tesla", "TSLA", "Optimus robot", "FSD"]},
    # Large cap
    {"name": "Oracle",          "ticker": "ORCL",  "keywords": ["Oracle", "ORCL", "Oracle AI"]},
    {"name": "Salesforce",      "ticker": "CRM",   "keywords": ["Salesforce", "CRM", "Agentforce"]},
    {"name": "Intel",           "ticker": "INTC",  "keywords": ["Intel", "INTC", "Gaudi"]},
    {"name": "Qualcomm",        "ticker": "QCOM",  "keywords": ["Qualcomm", "QCOM", "Snapdragon"]},
    {"name": "IBM",             "ticker": "IBM",   "keywords": ["IBM", "watsonx"]},
    {"name": "ServiceNow",      "ticker": "NOW",   "keywords": ["ServiceNow", "NOW"]},
    {"name": "Palantir",        "ticker": "PLTR",  "keywords": ["Palantir", "PLTR"]},
    {"name": "Snowflake",       "ticker": "SNOW",  "keywords": ["Snowflake", "SNOW"]},
    {"name": "Cloudflare",      "ticker": "NET",   "keywords": ["Cloudflare", "NET"]},
    {"name": "Datadog",         "ticker": "DDOG",  "keywords": ["Datadog", "DDOG"]},
    {"name": "MongoDB",         "ticker": "MDB",   "keywords": ["MongoDB", "MDB"]},
    {"name": "CrowdStrike",     "ticker": "CRWD",  "keywords": ["CrowdStrike", "CRWD"]},
    {"name": "Palo Alto",       "ticker": "PANW",  "keywords": ["Palo Alto Networks", "PANW"]},
    {"name": "Workday",         "ticker": "WDAY",  "keywords": ["Workday", "WDAY"]},
    {"name": "Intuit",          "ticker": "INTU",  "keywords": ["Intuit", "INTU"]},
    {"name": "Adobe",           "ticker": "ADBE",  "keywords": ["Adobe", "ADBE", "Firefly"]},
    {"name": "Synopsys",        "ticker": "SNPS",  "keywords": ["Synopsys", "SNPS"]},
    {"name": "Cadence",         "ticker": "CDNS",  "keywords": ["Cadence", "CDNS"]},
    {"name": "Applied Materials","ticker": "AMAT", "keywords": ["Applied Materials", "AMAT"]},
    {"name": "ASML (ADR)",      "ticker": "ASML",  "keywords": ["ASML"]},
    {"name": "Lam Research",    "ticker": "LRCX",  "keywords": ["Lam Research", "LRCX"]},
    {"name": "KLA Corp",        "ticker": "KLAC",  "keywords": ["KLA", "KLAC"]},
    {"name": "Arm Holdings",    "ticker": "ARM",   "keywords": ["Arm Holdings", "ARM"]},
    # AI-focused mid cap
    {"name": "C3.ai",           "ticker": "AI",    "keywords": ["C3.ai", " AI "]},
    {"name": "SoundHound AI",   "ticker": "SOUN",  "keywords": ["SoundHound", "SOUN"]},
    {"name": "Super Micro",     "ticker": "SMCI",  "keywords": ["Super Micro", "SuperMicro", "SMCI"]},
    {"name": "IonQ",            "ticker": "IONQ",  "keywords": ["IonQ", "IONQ"]},
    {"name": "Rigetti Computing","ticker": "RGTI",  "keywords": ["Rigetti", "RGTI"]},
    {"name": "Quantum Computing","ticker": "QUBT", "keywords": ["Quantum Computing Inc", "QUBT"]},
    {"name": "BigBear.ai",      "ticker": "BBAI",  "keywords": ["BigBear", "BBAI"]},
    {"name": "Recursion Pharma","ticker": "RXRX",  "keywords": ["Recursion", "RXRX"]},
    {"name": "Scale AI",        "ticker": "S",     "keywords": ["Scale AI"]},
    {"name": "Veeva Systems",   "ticker": "VEEV",  "keywords": ["Veeva", "VEEV"]},
    {"name": "Twilio",          "ticker": "TWLO",  "keywords": ["Twilio", "TWLO"]},
    {"name": "UiPath",          "ticker": "PATH",  "keywords": ["UiPath", "PATH"]},
    {"name": "Gitlab",          "ticker": "GTLB",  "keywords": ["GitLab", "GTLB"]},
    {"name": "Elastic",         "ticker": "ESTC",  "keywords": ["Elastic", "ESTC"]},
    {"name": "HashiCorp",       "ticker": "HCP",   "keywords": ["HashiCorp", "HCP"]},
    {"name": "Confluent",       "ticker": "CFLT",  "keywords": ["Confluent", "CFLT"]},
    {"name": "Informatica",     "ticker": "INFA",  "keywords": ["Informatica", "INFA"]},
    {"name": "Verint Systems",  "ticker": "VRNT",  "keywords": ["Verint", "VRNT"]},
    {"name": "Ceridian",        "ticker": "CDAY",  "keywords": ["Ceridian", "CDAY"]},
    {"name": "Sprinklr",        "ticker": "CXM",   "keywords": ["Sprinklr", "CXM"]},
    {"name": "Samsara",         "ticker": "IOT",   "keywords": ["Samsara", "IOT"]},
    {"name": "Asana",           "ticker": "ASAN",  "keywords": ["Asana", "ASAN"]},
    {"name": "monday.com",      "ticker": "MNDY",  "keywords": ["monday.com", "MNDY"]},
    {"name": "Zendesk",         "ticker": "ZEN",   "keywords": ["Zendesk", "ZEN"]},
    {"name": "Brainware AI",    "ticker": "BWAI",  "keywords": ["Brainware", "BWAI"]},
    {"name": "Luminar Tech",    "ticker": "LAZR",  "keywords": ["Luminar", "LAZR"]},
    {"name": "Mobileye",        "ticker": "MBLY",  "keywords": ["Mobileye", "MBLY"]},
    {"name": "Cruise (GM)",     "ticker": "GM",    "keywords": ["Cruise autonomous", "GM AI"]},
    {"name": "Aurora Innovation","ticker": "AUR",  "keywords": ["Aurora Innovation", "AUR"]},
    {"name": "Symbotic",        "ticker": "SYM",   "keywords": ["Symbotic", "SYM"]},
    {"name": "Legalzoom",       "ticker": "LZ",    "keywords": ["LegalZoom", "LZ"]},
    {"name": "Duolingo",        "ticker": "DUOL",  "keywords": ["Duolingo", "DUOL"]},
    {"name": "Chegg",           "ticker": "CHGG",  "keywords": ["Chegg", "CHGG"]},
    {"name": "Coursera",        "ticker": "COUR",  "keywords": ["Coursera", "COUR"]},
    {"name": "2U Inc",          "ticker": "TWOU",  "keywords": ["2U Inc", "TWOU"]},
    {"name": "Genie Energy",    "ticker": "GNE",   "keywords": ["Genie Energy", "GNE"]},
    {"name": "Veritone",        "ticker": "VERI",  "keywords": ["Veritone", "VERI"]},
    {"name": "LivePerson",      "ticker": "LPSN",  "keywords": ["LivePerson", "LPSN"]},
    {"name": "Limelight/Edgio", "ticker": "EGIO",  "keywords": ["Edgio", "EGIO"]},
    {"name": "Appian",          "ticker": "APPN",  "keywords": ["Appian", "APPN"]},
    {"name": "Olo",             "ticker": "OLO",   "keywords": ["Olo", " OLO "]},
    {"name": "Five9",           "ticker": "FIVN",  "keywords": ["Five9", "FIVN"]},
    {"name": "NICE Ltd",        "ticker": "NICE",  "keywords": ["NICE Ltd", "NICE"]},
    {"name": "Bandwidth",       "ticker": "BAND",  "keywords": ["Bandwidth Inc", "BAND"]},
    {"name": "Lunit",           "ticker": "LUNIT",  "keywords": ["Lunit"]},
    {"name": "iRobot",          "ticker": "IRBT",  "keywords": ["iRobot", "IRBT"]},
    {"name": "Intuitive Surgical","ticker": "ISRG","keywords": ["Intuitive Surgical", "ISRG", "da Vinci"]},
    {"name": "Boston Scientific","ticker": "BSX",  "keywords": ["Boston Scientific", "BSX"]},
    {"name": "Medtronic",       "ticker": "MDT",   "keywords": ["Medtronic", "MDT"]},
    {"name": "Nvidia partner: Dell","ticker": "DELL","keywords": ["Dell AI", "Dell NVDA", "Dell PowerEdge AI"]},
    {"name": "HP Enterprise",   "ticker": "HPE",   "keywords": ["HPE AI", "HP Enterprise AI"]},
    {"name": "Pure Storage",    "ticker": "PSTG",  "keywords": ["Pure Storage", "PSTG"]},
    {"name": "NetApp",          "ticker": "NTAP",  "keywords": ["NetApp", "NTAP"]},
    {"name": "Roper Technologies","ticker": "ROP", "keywords": ["Roper Technologies", "ROP"]},
    {"name": "Tyler Technologies","ticker": "TYL", "keywords": ["Tyler Technologies", "TYL"]},
    {"name": "SS&C Technologies","ticker": "SSNC", "keywords": ["SS&C", "SSNC"]},
    {"name": "OpenAI (private)","ticker": "N/A",   "keywords": ["OpenAI", "ChatGPT", "GPT-5", "o3"]},
    {"name": "Anthropic (private)","ticker": "N/A","keywords": ["Anthropic", "Claude AI"]},
    {"name": "xAI (private)",   "ticker": "N/A",   "keywords": ["xAI", "Grok AI", "Elon Musk AI"]},
    {"name": "Mistral (private)","ticker": "N/A",  "keywords": ["Mistral AI"]},
    {"name": "Cohere (private)", "ticker": "N/A",  "keywords": ["Cohere AI"]},
    {"name": "Perplexity (private)","ticker": "N/A","keywords": ["Perplexity AI"]},
]
