# User-curated watchlist. Order here = display order on the page.
# Private companies (no ticker) are kept for visibility but can't be fetched
# from Finnhub (which is ticker-based) — they will show no news.
AI_COMPANIES = [
    {"name": "美光 Micron",     "ticker": "MU",    "keywords": ["Micron", "MU"]},
    {"name": "闪迪 SanDisk",    "ticker": "SNDK",  "keywords": ["SanDisk", "SNDK"]},
    {"name": "迈威尔 Marvell",  "ticker": "MRVL",  "keywords": ["Marvell", "MRVL"]},
    {"name": "AMD",             "ticker": "AMD",   "keywords": ["AMD", "Advanced Micro Devices"]},
    {"name": "Nebius",          "ticker": "NBIS",  "keywords": ["Nebius", "NBIS"]},
    {"name": "Semtech",         "ticker": "SMTC",  "keywords": ["Semtech", "SMTC"]},
    {"name": "英伟达 NVIDIA",   "ticker": "NVDA",  "keywords": ["NVIDIA", "Nvidia", "NVDA"]},
    {"name": "谷歌 Alphabet",   "ticker": "GOOGL", "keywords": ["Google", "Alphabet", "GOOGL", "Gemini", "DeepMind", "Waymo"]},
    {"name": "微软 Microsoft",  "ticker": "MSFT",  "keywords": ["Microsoft", "MSFT", "Copilot"]},
    {"name": "苹果 Apple",      "ticker": "AAPL",  "keywords": ["Apple", "AAPL"]},
    {"name": "Meta",            "ticker": "META",  "keywords": ["Meta", "META", "Facebook", "Instagram", "Llama"]},
    {"name": "亚马逊 Amazon",   "ticker": "AMZN",  "keywords": ["Amazon", "AMZN", "AWS"]},
    {"name": "特斯拉 Tesla",    "ticker": "TSLA",  "keywords": ["Tesla", "TSLA"]},
    {"name": "台积电 TSMC",     "ticker": "TSM",   "keywords": ["TSMC", "Taiwan Semiconductor", "TSM"]},
    {"name": "博通 Broadcom",   "ticker": "AVGO",  "keywords": ["Broadcom", "AVGO"]},
    {"name": "英特尔 Intel",    "ticker": "INTC",  "keywords": ["Intel", "INTC"]},
    {"name": "高通 Qualcomm",   "ticker": "QCOM",  "keywords": ["Qualcomm", "QCOM", "Snapdragon"]},
    {"name": "Arm",             "ticker": "ARM",   "keywords": ["Arm Holdings", "Arm", "ARM"]},
    {"name": "AAOI 应用光电",   "ticker": "AAOI",  "keywords": ["Applied Optoelectronics", "AAOI"]},
    {"name": "Astera Labs",     "ticker": "ALAB",  "keywords": ["Astera Labs", "Astera", "ALAB"]},
    {"name": "AXT",             "ticker": "AXTI",  "keywords": ["AXT", "AXTI"]},
    {"name": "康宁 Corning",    "ticker": "GLW",   "keywords": ["Corning", "GLW"]},
    {"name": "Lumentum",        "ticker": "LITE",  "keywords": ["Lumentum", "LITE"]},
    {"name": "黑莓 BlackBerry", "ticker": "BB",    "keywords": ["BlackBerry", "BB"]},
    {"name": "Robinhood",       "ticker": "HOOD",  "keywords": ["Robinhood", "HOOD"]},
    {"name": "Cloudflare",      "ticker": "NET",   "keywords": ["Cloudflare", "NET"]},
]
